version: "3.8"

services:

  mariadb:
    image: mariadb:latest
    container_name: uptime_monitor_mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/mariadb-init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - monitor-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: uptime_monitor_clickhouse
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse/clickhouse-init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    networks:
      - monitor-network

  node-monitor-api:
    build:
      context: .
      dockerfile: docker/APIDockerfile
    image: node-monitor-api:latest
    ports:
      - "127.0.0.1:8081:8081"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${API_DB_USER}
      MYSQL_PASSWORD: ${API_DB_PASSWORD}
    depends_on:
      - mariadb
      - clickhouse
    networks:
      - monitor-network

  node-monitor:
    build:
      context: .
      dockerfile: docker/MonitorDockerfile
    image: node-monitor:latest
    ports:
      - "127.0.0.1:9091:9091"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MONITOR_DB_USER}
      MYSQL_PASSWORD: ${MONITOR_DB_PASSWORD}
      CLICKHOUSE_USER: ${CLICKHOUSE_MONITOR_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_MONITOR_PASSWORD}
    depends_on:
      - mariadb
      - clickhouse
    networks:
      - monitor-network

  node-test:
    build:
      context: .
      dockerfile: docker/TestDockerfile
    image: node-test:latest
    profiles:
      - test

volumes:
  clickhouse_data:
  mariadb_data:

networks:
  monitor-network:
    driver: bridge